### PR TITLE
fix(el): defer heartbeat until bind response

### LINKED ISSUE #49: bug: enquire_link sent before bind causes connection failure
## Problem

When `enquireLink.auto` is set to `true`, the `connect()` method in `client.ts` (line 73) immediately sends an `enquire_link` PDU **before** the bind handshake completes:

```typescript
connect({ url }: { url: string }): void {
    const { host, port } = this.validateUrl(url);
    this.session.connect({ host, port });

    if (this._enquireLink.auto && this._enquireLink.interval) {
        this.enquireLink();  // <-- sent before bind!
        this.autoEnquireLink(this._enquireLink.interval);
    }
}
```

Per the SMPP specification, `enquire_link` should only be sent after a successful bind. Sending it before bind causes the SMSC to reject or drop the connection.

### Option A: Remove the immediate call (minimal change)

Simply delete line 73 (`this.enquireLink()`), keeping only `this.autoEnquireLink()`. The first heartbeat would then fire after the configured interval (default 20s), by which time the bind is complete.

```diff
 if (this._enquireLink.auto && this._enquireLink.interval) {
-    this.enquireLink();
     this.autoEnquireLink(this._enquireLink.interval);
 }
```

**Pros**: One-line change, minimal risk
**Cons**: Relies on the interval being longer than the bind time (practically always true, but not guaranteed by protocol)

### Option B: Start heartbeat after bind response

Move `autoEnquireLink()` into bind response listeners so it only starts after a successful bind:

```typescript
connect({ url }: { url: string }): void {
    const { host, port } = this.validateUrl(url);
    this.session.connect({ host, port });

    if (this._enquireLink.auto && this._enquireLink.interval) {
        const interval = this._enquireLink.interval;
        const onBound = () => { this.autoEnquireLink(interval); };
        this.on('bind_transceiver_resp', onBound);
        this.on('bind_transmitter_resp', onBound);
        this.on('bind_receiver_resp', onBound);
    }
}
```

**Pros**: Protocol-correct, heartbeat only starts after confirmed bind
**Cons**: Larger change, needs to handle all three bind types

## Question

Which approach would you prefer? I'm happy to submit a PR for either option.

### PR DESCRIPTION
**Pull request by p0we7**
## Summary

Fixes SMPP protocol violation where `enquire_link` was sent before
bind completed, causing SMSC to reject the connection.

## Changes

- Add `_bound` state tracking to Session with getter/setter
- Auto-reply incoming `enquire_link` with correct sequence_number
- Reset bound state on disconnect/end events
- Defer `autoEnquireLink` until `bind_*_resp` with status === 0
- Move `enquire_link_resp` to `SendCommandName`
- Add `bound` public getter to Client and IClient interface

Closes #49

### CODE REVIEW

**Comment by joaogervasoni** [comment]
Thanks for your contribution 🤝

I have some ideas about this item, so I want to run it, test it, and suggest some things. I'll get back soon.

File: src/types/pdu.ts [hunk 1]
```diff
@@ -62,7 +63,6 @@ export type ResponseCommandName =
     | 'replace_sm_resp'
     | 'cancel_sm_resp'
     | 'bind_transceiver_resp'
-    | 'enquire_link_resp'
     | 'submit_multi_resp'
```
Comment (joaogervasoni) [inline src/types/pdu.ts]: In that case, did you change it because the server is sending the EnquireLink?

File: src/session.ts [hunk 2]
```diff
@@ -98,8 +111,18 @@ export default class Session {
...
                 if (data) {
                     const pdu = this.PDU.readPdu(data);
+                    this.logger.debug(`${pdu.command} - received`, pdu);
                     this.socket.emit('pdu', pdu);
                     this.socket.emit(pdu.command, pdu);
+
+                    if (pdu.command === 'enquire_link') {
+                        const dto = getDTO<EnquireLinkRespFunction>('enquire_link_resp')({});
+                        this.PDU.call({ command: 'enquire_link_resp', sequenceNumber: pdu.sequence_number, dto });
+                    }
```
Comment (joaogervasoni) [inline src/session.ts]: If we are to allow the enquireLink coming from the server, this DTO would need to be used by the normal response flow: 

```js
if (data) {
  const pdu = this.PDU.readPdu(data);
```

File: src/session.ts [hunk 3]
```diff
@@ -30,13 +31,16 @@ import {
     SubmitMultiFunction,
 } from './types';
 
+const bindRespCommands = new Set(['bind_transceiver_resp', 'bind_transmitter_resp', 'bind_receiver_resp']);
```
Comment (joaogervasoni) [inline src/session.ts]: Don't leave this item specified, my fault, but I avoid using map and set, not because it would be bad, but to maintain a compatible and performant project always using objects.

File: src/types/pdu.ts (hunk 1 above)
Comment (p0we7) [reply src/types/pdu.ts]: Yes, exactly. Since the SMSC can initiate `enquire_link` requests (as we observed in production), the client must respond with `enquire_link_resp`. That makes it a command the client *sends*, so it belongs in `SendCommandName`. Previously it was in `ResponseCommandName` but was never actually usable from the client side — moving it here makes the type accurately reflect reality and lets `PDU.call()` accept it.

File: src/session.ts (hunk 2 above)
Comment (p0we7) [reply src/session.ts]: That's a good point. The current approach hard-codes the auto-reply inside `initResponseRead`, which bypasses the normal event-driven flow. A cleaner design would be to let `enquire_link` propagate through the normal `pdu` event path and have the response handled at a higher level (e.g., in `Client`), so users can still observe or override the behavior if needed. I'm open to refactoring this — happy to move the auto-reply logic into `Client` so that `Session` stays as a thin transport layer.

File: src/session.ts (hunk 3 above)
Comment (p0we7) [reply src/session.ts]: Understood, will replace `Set` with a plain object lookup. For example:

```ts
const bindRespCommands: Record<string, true> = {
    bind_transceiver_resp: true,
    bind_transmitter_resp: true,
    bind_receiver_resp: true,
};
```

This keeps the same O(1) lookup semantics while staying consistent with the project conventions. I'll push an update.

Comment (joaogervasoni) [reply src/session.ts]: Array would work well 🙏

File: src/types/pdu.ts (hunk 1 above)
Comment (joaogervasoni) [reply src/types/pdu.ts]: I've always handled the EnquireLink on the client side, but there's a possibility the server could handle it.

We'll need to make it work so that the EnquireLink works for either side, with the necessary validations.

What I suggest is focusing the PR on the bound getter part and sending the EnquireLink from the client after binding, if that option is enabled in the client's class configuration.

File: src/session.ts (hunk 2 above)
Comment (joaogervasoni) [reply src/session.ts]: nice!

**Comment by p0we7** [comment]
Thanks for the guidance — I updated the branch to keep this PR focused on the scope you suggested.
                                                                                                                                                                    
  What I changed                                                                                             

  1. Kept the PR focused on bind + client-side heartbeat flow
    - Heartbeat auto-send remains triggered only after successful bind (command_status === 0) in Client.
    - bound state exposure/flow is preserved as implemented.
  2. Reverted enquire_link_resp scope expansion
    - Removed the in-session automatic enquire_link_resp handling I had added before.
    - Moved enquire_link_resp back to ResponseCommandName (so this PR does not expand into server-initiated heartbeat handling yet).
  3. Applied your style preference (no Set/Map here)
    - Replaced Set with Array for bind response command matching in session.ts.
    - Updated .has() to .includes() accordingly.

  Result

  - The branch now stays aligned with the PR goal:
  bound-driven behavior + send enquire_link from client only after bind (when enabled).
  - Build passes successfully.

File: src/client.ts
Comment (joaogervasoni) [inline src/client.ts:203]: Adding a validation to prevent repeated timeout calls in case of one or more binds.

```suggestion
    if (!this._enquireLinkTimeout) {
        scheduleNext();
    }
```
